### ISSUE TITLE
rake assets:precompile error

### ISSUE THREAD

**Issue by nebulade** [d4l3k/WebSync#163]
I was following the brief instructions in the Readme to get a local deployment up and running and ended up with a assets:precompile error where I simply can't get my head around.

I installed the dependencies as follows:
```
bundle install
npm install
bower install
rake assets:precompile
```
And rake fails with
```
 100.00% documented
rake aborted!
LoadError: cannot load such file -- sprockets/sass/importer
  (in /home/nebulon/projects/WebSync/assets/bower_components/seiyria-bootstrap-slider/sass/slider.scss)
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-sass-1.3.1/lib/sprockets/sass/sass_template.rb:82:in `sass_options'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-sass-1.3.1/lib/sprockets/sass/sass_template.rb:53:in `evaluate'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/context.rb:197:in `block in evaluate'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/context.rb:194:in `each'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/context.rb:194:in `evaluate'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:374:in `new'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:374:in `block in build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:373:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:94:in `block in build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/caching.rb:51:in `cache_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:93:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:287:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:61:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:105:in `each'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/processed_asset.rb:16:in `initialize'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:374:in `new'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:374:in `block in build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:373:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:94:in `block in build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/caching.rb:51:in `cache_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:93:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:287:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:61:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:377:in `new'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:377:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:94:in `block in build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/caching.rb:51:in `cache_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:93:in `build_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/base.rb:287:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/index.rb:61:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:257:in `benchmark'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:210:in `find_asset'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:119:in `block in compile'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:118:in `each'
/home/nebulon/projects/WebSync/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.2/lib/sprockets/manifest.rb:118:in `compile'
/home/nebulon/projects/WebSync/Rakefile:27:in `block (2 levels) in initialize'
Tasks: TOP => assets:precompile
```
The `sprockets-sass` gem is installed.

Do I miss some obvious dependency installation step?

**Comment by d4l3k** [comment]
I've encountered this error in the past. Try running `bundle exec rake
assets:precompile`. It seems to be an issue with how bundle is configured,
so if you find out what's causing it I'd love to know.

**Comment by d4l3k** [comment]
I've encountered this error in the past. Try prefixing your commands with `bundle exec`. Ex:
```
bundle exec rake assets:precompile
```
I think it's an issue with how your ruby environment and bundler are configured, but I'm sure the exact fix.

If you have any other questions please let me know.

**Comment by nebulade** [comment]
it worked with prefixing it with `bundle exec` also thanks for updating the Readme.md
I probably won't be of much help with bundle and rake issues, as I am coming from the nodejs community without much clue of the ruby ecosystem.

I created a pull request #164 of additional dependencies I came across.

**Comment by nebulade** [comment]
Actually the same goes for `rackup` it will have issues when not prefixed with `bundle exec`

```
LoadError: cannot load such file -- rack/protection/http_origin
```

Looks like the very same root cause.

**Comment by d4l3k** [comment]
Yeah, it's the same issue. `bundle exec` sets certain environment variables that force the commands to use the Bundler version of the gems. 

I'm used to using RVM + `rubygems-bundler` which makes `bundle exec` unneeded. For more information see https://rvm.io/integration/bundler

That page makes it sound like you can install `rubygems-bundler` and run `gem regenerate_binstubs` to get the same effect.
